name: Main Testing

on:
  push:
    branches: [ "main" ]

jobs:
  
  build_and_push_to_registry:

    # name: Build and push Docker Frontend image to Docker Hub
    # if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scrybe_frontend


    steps:
          
      - name: Check out the repo
        uses: actions/checkout@v3 
    
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}          
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Get Current Date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ steps.date.outputs.date }}
        
      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ steps.date.outputs.date }}


  
  build_and_push_to_registry_backend:

    # name: Build and push Docker image to Docker Hub
    # if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
   

    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: change directory
        run: cd backend/app


      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}          
                        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: vicdam/scrybebackend
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: ./customersupport.web/backend/Dockerfile
          context: .
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }} 

  Deploy: 
    needs: [ build_and_push_to_registry_backend , build_and_push_to_registry ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Pull from GitHub
        uses: appleboy/ssh-action@master

        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
          script: |
            docker-compose up -d .             
            


        
